#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER $DB_USER WITH PASSWORD '$DB_USER_PASS';
GRANT CONNECT ON DATABASE $POSTGRES_DB TO $DB_USER;
GRANT ALL ON SCHEMA public TO $DB_USER;
EOSQL
