"""Initial

Revision ID: 26991f830d22
Revises: 
Create Date: 2023-08-30 23:11:04.967668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26991f830d22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_table('actions')
    op.drop_table('trackers')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BIGINT(), server_default=sa.text("nextval('users_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_pk'),
    postgresql_ignore_search_path=False
    )
    op.create_table('trackers',
    sa.Column('tracker_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('track_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('track_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('category_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('action_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration', postgresql.INTERVAL(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.action_id'], name='trackers_action_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='trackers_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tracker_id', name='trackers_pkey')
    )
    op.create_table('actions',
    sa.Column('action_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name='actions_category_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='actions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id', name='actions_pkey'),
    sa.UniqueConstraint('user_id', 'action_name', 'category_id', name='actions_action_name_category_id_user_id_key_unique')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='actions_category_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', name='actions_category_pkey'),
    sa.UniqueConstraint('user_id', 'category_name', name='unique_user_id_category_name')
    )
    # ### end Alembic commands ###
