from .categories_handlers import register_categories_handlers
from .actions_handlers import register_actions_handlers
from .tracker_handlers import register_tracker_handlers
from .reports_handlers import register_report_handlers
from .common_handles import register_common_handlers

